name: Node.js CI

on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4
    - run: npm install
    - run: npm run build
    - run: pm2 restart next-js
