name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2

    - run: |
        echo "Hello World"
        npm install
        npm run build
        npm run test
        pm2 restart next-app
      